### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tianchu**
### What does this PR do?

Update dependencies

### Motivation

https://github.com/DataDog/datadog-lambda-layer-python/pull/26

### CODE REVIEW

**Comment by mbelang** [comment]
Hi @tianchu. Do you have an estimate on this as it is a blocker for us right now. Than you

**Comment by tianchu** [comment]
@mbelang Do you use pip or a requirements.txt to manage python dependencies? If so, you can list `ddtrace` with the desired version in your projects' requirements.txt directly, which would be override the `ddtrace` provided by the layer.

**Comment by mbelang** [comment]
No i'm not. We are using poetry which does a better job a dependency resolution and there is obviously a conflict between our lib and this one as our lib uses the latest of datadog's

**Comment by tianchu** [comment]
So you installs `datadog-lambda` using poetry? Does this workaround work for you https://github.com/sdispater/poetry/issues/697? 

You can also probably remove `datadog-lambda` from poetry, but instead use our serverless framework plugin: https://github.com/DataDog/serverless-plugin-datadog. Our plugin will install datadog-lambda as a AWS Lambda Layer instead of a python package, which would avoid causing conflicts with your own dependencies.

**Comment by mbelang** [comment]
I decided to install datadog-lambda from git instead. I'm testing it ATM

**Comment by tianchu** [comment]
The upgrade is blocked by a bug in the latest version (0.31.0) of `datadogpy`: https://github.com/DataDog/datadogpy/pull/480

**Pull request merged**
